# Generated by Django 4.2.13 on 2024-06-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=100)),
                ("amount", models.IntegerField()),
                ("status", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("termly", "Termly Payment")],
                        default="termly",
                        max_length=20,
                    ),
                ),
                ("term_end_date", models.DateTimeField()),
            ],
        ),
    ]
