# Generated by Django 4.2.13 on 2024-06-14 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("student_management", "0001_initial"),
        ("class_management", "0001_initial"),
        ("performance_tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportcard",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_card",
                to="student_management.student",
            ),
        ),
        migrations.AddField(
            model_name="performance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="student_management.student",
            ),
        ),
        migrations.AddField(
            model_name="performance",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="class_management.subject",
            ),
        ),
        migrations.AddField(
            model_name="extracurricularactivity",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extra_curricular_activities",
                to="student_management.student",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="student_management.student",
            ),
        ),
    ]
