# Generated by Django 4.2.13 on 2024-06-14 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("school_management", "0001_initial"),
        ("leaderboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboard",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaderboards",
                to="school_management.school",
            ),
        ),
    ]
