# Generated by Django 4.2.13 on 2024-06-14 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("school_management", "0001_initial"),
        ("subject_management", "0001_initial"),
        ("exam_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questions",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="school_management.school",
            ),
        ),
        migrations.AddField(
            model_name="questions",
            name="subtopic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="subject_management.subtopic",
            ),
        ),
        migrations.AddField(
            model_name="questions",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="subject_management.topic",
            ),
        ),
        migrations.AddField(
            model_name="option",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="exam_management.questions",
            ),
        ),
    ]
