# Generated by Django 4.2.13 on 2024-06-14 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("school_management", "0001_initial"),
        ("student_management", "0001_initial"),
        ("class_management", "0001_initial"),
        ("exam_management", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="manualscore",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manual_scores",
                to="student_management.student",
            ),
        ),
        migrations.AddField(
            model_name="manualscore",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manual_scores",
                to="class_management.subject",
            ),
        ),
        migrations.AddField(
            model_name="manualscore",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="given_scores",
                to="class_management.teacher",
            ),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="questions",
            field=models.ManyToManyField(to="exam_management.questions"),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="student_exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="student_management.studentexam",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="exam_management.examcategory",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="school_management.school",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="class_management.subject",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_exams",
                to="class_management.teacher",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="manualscore",
            unique_together={("student", "subject", "date_assigned")},
        ),
    ]
