# Generated by Django 4.2.13 on 2024-06-14 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("exam_management", "0002_initial"),
        ("class_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BehavioralAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=20)),
                ("year", models.IntegerField()),
                ("behavior", models.CharField(max_length=255)),
                ("score", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="EnrollmentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_approved", models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=100)),
                ("is_independent_learner", models.BooleanField(default=False)),
                ("grade", models.CharField(default="N/A", max_length=50)),
                (
                    "student_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("parent_contact", models.CharField(blank=True, max_length=100)),
                (
                    "enrolled_class",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="class_management.class",
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        related_name="students", to="class_management.subject"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("score", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_takers",
                        to="exam_management.exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taken_exams",
                        to="student_management.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubjectCombination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_combination",
                        to="student_management.student",
                    ),
                ),
                ("subjects", models.ManyToManyField(to="class_management.subject")),
            ],
        ),
        migrations.CreateModel(
            name="StudentPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=20)),
                ("year", models.IntegerField()),
                ("grade", models.CharField(max_length=5)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performances",
                        to="student_management.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="class_management.subject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentExamAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exam_management.questions",
                    ),
                ),
                (
                    "student_answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exam_management.option",
                    ),
                ),
                (
                    "student_exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management.studentexam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("participation_level", models.CharField(max_length=50)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="student_management.student",
                    ),
                ),
            ],
        ),
    ]
