# Generated by Django 4.2.13 on 2024-06-14 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("student_management", "0001_initial"),
        ("school_management", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("class_management", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="enrollmentrequest",
            name="enrolled_class",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="class_management.class",
            ),
        ),
        migrations.AddField(
            model_name="enrollmentrequest",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="school_management.school",
            ),
        ),
        migrations.AddField(
            model_name="enrollmentrequest",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="student_management.student",
            ),
        ),
        migrations.AddField(
            model_name="enrollmentrequest",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="class_management.teacher",
            ),
        ),
        migrations.AddField(
            model_name="behavioralassessment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="behavioral_assessments",
                to="student_management.student",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentexamanswer",
            unique_together={("student_exam", "question")},
        ),
    ]
